$ 
$ =======================================================================
$   (c) Copyright Hewlett-Packard Development Company, L.P., 2008
$
$   This program is free software: you can redistribute it and/or modify
$   it under the terms of version 2 the GNU General Public License as
$   published by the Free Software Foundation.
$   
$   This program is distributed in the hope that it will be useful,
$   but WITHOUT ANY WARRANTY; without even the implied warranty of
$   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
$   GNU General Public License for more details.
$   
$   You should have received a copy of the GNU General Public License
$   along with this program.  If not, see <http://www.gnu.org/licenses/>.
$
$ =======================================================================
$
$
$ HISTORY
$ 
$ @(#)$RCSfile: rmfset.msg,v $ $Revision: 1.1.4.3 $ (DEC) $Date: 1999/03/29 14:47:44 $
$ 

$ /*
$  * X/OPEN message catalogue
$  */

$quote "

$set 1
USAGE	"usage: %s [-f] domain set \n"
2	"%s: error locking '%s'; [%d] %s\n"
3	"%s: Domain directory '%s' does not exist\n"
4	"%s: error getting '%s' stats; [%d] %s\n"
5	"%s: cannot execute. Another AdvFS command is currently claiming exclusive use of the specified domain.\n"
6	"%s: error locking '%s'.\n"
7	"%s: Error = [%d] %s\n"
8	"%s: error unlocking '%s'; [%d] %s\n"
9	"%s: can't delete file set '%s' from domain '%s'\n"
10	"%s: error = %s\n"
11	"%s: remove fileset %s? [y/n] "
12	"\nPermission denied - user must be root to run %s.\n\n"
