$ =======================================================================
$   (c) Copyright Hewlett-Packard Development Company, L.P., 2008
$
$   This program is free software: you can redistribute it and/or modify
$   it under the terms of version 2 the GNU General Public License as
$   published by the Free Software Foundation.
$   
$   This program is distributed in the hope that it will be useful,
$   but WITHOUT ANY WARRANTY; without even the implied warranty of
$   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
$   GNU General Public License for more details.
$   
$   You should have received a copy of the GNU General Public License
$   along with this program.  If not, see <http://www.gnu.org/licenses/>.
$
$ =======================================================================

$
$ Copyright (c) 2002-2004 Hewlett-Packard Development Company, L.P.
$ 

$quote "

$set S_LIBRARY1
LIBRARY15	"%s: cannot access device %s; [%d] %s\n"
LIBRARY16	"%s: unable to open directory <%s>; [%d] %s\n"
LIBRARY17	"%s: device in use by domain %s; device %s\n"
LIBRARY18       "Unable to create directory %s; [%d] %s\n"

$ Extend related messages
LIBRARY29	"%s: error processing specified name %s\n"
LIBRARY30	"%s: filesystem and device mismatch: %s, %s\n"
LIBRARY31	"%s: size argument requires a device name\n"
LIBRARY32	"%s: Could not open %s\n"
LIBRARY33	"%s: Could not read link %s\n"
LIBRARY34	"%s: Disk size of %s is %ld\n"
LIBRARY35	"%s: Error extending %s: %s (%ld)\n"
LIBRARY36	"%s: Extended %s from %ld to %ld blocks\n"
LIBRARY37	"%s: Error extending %s: filesystem activation failure\n"
LIBRARY38	"%s: Error extending %s: extend size too small\n"
LIBRARY39	"%s: Error extending %s: device contains swap\n"
LIBRARY40	"%s: Extended %s to %ld blocks\n"

