$ =======================================================================
$   (c) Copyright Hewlett-Packard Development Company, L.P., 2008
$
$   This program is free software: you can redistribute it and/or modify
$   it under the terms of version 2 the GNU General Public License as
$   published by the Free Software Foundation.
$   
$   This program is distributed in the hope that it will be useful,
$   but WITHOUT ANY WARRANTY; without even the implied warranty of
$   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
$   GNU General Public License for more details.
$   
$   You should have received a copy of the GNU General Public License
$   along with this program.  If not, see <http://www.gnu.org/licenses/>.
$
$ =======================================================================

$ *****************************************************************
$ *                                                               *
$ *  Copyright (c) 2002 Hewlett-Packard Development Company, L.P. *
$ *                                                               *
$ *****************************************************************

$ HISTORY
$
$

$quote "
$set MS_TRASHCAN

TCUSAGE         "usage: %s [-m trashcan | -r] directory ...\n"
E_ATTACH        "%s: cannot attach trashcan '%s' to '%s'; %s\n"
E_DETACH        "%s: cannot detach trashcan from '%s'; %s\n"
E_STAT          "%s: cannot access '%s'; %s\n"
E_ADVFS         "%s: %s is not in an AdvFS filesystem\n"
E_NOTRASHCAN    "%s: '%s' has no trashcan\n"
E_ATTACHED1     "    '%s' attached to '%s'\n"
E_ATTACHED2     "' attached to '%s'\n"
E_DETACHED      "    '%s' detached\n"
E_NOMEM         "%s: insufficient memory.\n"
